### ISSUE TITLE
Yin throws RangeError

### ISSUE THREAD

**Issue by synchronisator** [techpotatoes/pitch_detector_dart#2]
Hi,
I am trying to use your library. The recording package you use in your example (flutter_audio_capture) does not work on my machines. Android and Linux are only throwing errors.
So i tried to use the "record" package instead. 
I recieve a  stream of UInt8 here instead of double. And the yin-difference has some problem with this input.
Maybe you have an idea.
This is the output. Firstline is the casted UintList to List<double>

```
I/flutter (18180): [255.0, 249.0, 16.0, 128.0, 1.0, 127.0, 252.0, 43.0, 146.0, 8.0, 0.0]
E/flutter (18180): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..10: 11
E/flutter (18180): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
E/flutter (18180): #1      Yin._difference (package:pitch_detector_dart/algorithm/yin.dart:75:49)
E/flutter (18180): #2      Yin.getPitch (package:pitch_detector_dart/algorithm/yin.dart:36:5)
E/flutter (18180): #3      PitchDetector.getPitch (package:pitch_detector_dart/pitch_detector.dart:14:28)
```

Code is almost copied from your example with some changes for the record-package:
```
class _PitchPageState extends State<PitchPage> {
  final AudioRecorder _audioRecorder = AudioRecorder();
  final PitchDetector pitchDetectorDart = PitchDetector(44100, 2000);
  final PitchHandler pitchupDart = PitchHandler(InstrumentType.guitar);

  String note = "";
  String status = "Click on start";

  Future<void> _startCapture() async {

    if (await _audioRecorder.hasPermission()) {
      final Stream<Uint8List> stream = await _audioRecorder.startStream(const RecordConfig(
        encoder: AudioEncoder.aacHe,
      ));
      stream
        ..handleError(onError)
        ..listen((Uint8List event) => listener(event.map((int i) => i.toDouble()).toList()));
    }

    setState(() {
      note = "";
      status = "Play something";
    });
  }
```
I am very thankful for any hint.
Thanks!

**Comment by ekuleshov** [comment]
@synchronisator have you tried to convert your input to a list of doubles? E.g. divide each uint8 by 1000

**Comment by synchronisator** [comment]
I got the flutter_audio_capture package to work. And the input is completely different to what i got from the record-package.

flutter_audio_capture:
```
[-0.012298583984375, -0.011810302734375, -0.011444091796875, -0.010650634765625, -0.011383056640625, -0.010284423828125, -0.01068115234375, -0.00946044921875, -0.009979248046875, -0.008941650390625, -0.008544921875, -0.008697509765625, -0.007415771484375, -0.006866455078125, -0.00750732421875, -0.005889892578125, -0.005584716796875, -0.00592041015625, -0.00445556640625, -0.004608154296875, -0.00311279296875, -0.003448486328125, -0.002593994140625, -0.002166748046875, -0.001220703125, -0.0009765625, -0.000518798828125, 0.00115966796875, 0.000396728515625, 0.00201416015625, 0.002288818359375, 0.002593994140625, 0.003753662109375, 0.00457763671875, 0.00408935546875, 0.005950927734375, 0.005859375, 0.007110595703125, 0.0074462890625, 0.007843017578125, 0.009368896484375, 0.00982666015625, 0.010040283203125, 0.01123046875, 0.0123291015625, 0.011871337890625, 0.01385498046875, 0.01287841796875, 0.015380859375, 0.014923095703125, 0.016448974609375, 0.0166015625, 0.017852783203125, 0.018341064453125, 0.0179748535156
```
record:
```
[255.0, 249.0, 16.0, 128.0, 1.0, 127.0, 252.0, 43.0, 146.0, 8.0, 0.0]
```

Maybe it would be a good idea to specify what format the audiostream must have, to work with this package. I have no idea how to convert one into the other.
But for me personally this problem is kind of solved by getting the other package to work. But thats not a general solution.

**Comment by techpotatoes** [comment]
Sorry it took so long. I've updated the sample to use newer versions.

I'll write an example on how to use  record-package as well.

**Comment by techpotatoes** [comment]
Have a look at https://github.com/techpotatoes/pitchup_flutter_sample 

I updated it to use a more widely available recording library. Please test it. 

Cheers
